---
application:
  name: "micoleaodublado"
  project: "NovoAddon"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "mongo"
  version: "3.6"
routers:
- name: "main-micoleaodublado"
  routes:
  - application_name: "micoleaodublado"
    paths:
    - "/*"
